### ISSUE TITLE
try-catch-finally

### ISSUE THREAD

**Issue by burcukaptikacti** [oykunsay/HospitalManagementSystem#7]
In the method below why did you use finally? And not others? 
 
 https://github.com/oykunsay/HospitalManagementSystem/blob/bb3626bcd20d4449806160deddbc472a9b9bb027/HospitalManagementSystem/src/Model/Appointment.java#L34-L60

**Comment by oykunsay** [comment]
I used to finally to close the connection and I think I've should use it for others too.

**Comment by burcukaptikacti** [comment]
Updaate code and commit
